# Generated by Django 4.2.7 on 2024-11-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="is_paid",
            new_name="repayment",
        ),
    ]
